### ISSUE TITLE
Chat not working

### ISSUE THREAD

**Issue by BenutzerEinsZweiDrei** [reorproject/reor#2]
- I downloaded
https://huggingface.co/TheBloke/Llama-2-7B-GGUF/resolve/main/llama-2-7b.Q2_K.gguf?download=true
- and used it as "new local model".
- I tried with token limit 200 and 2000 and 4000
- i create one and then two md files
- i wrote "hello" in chat

Chat is not working. It doesnt reply anything.

- I am on Windows 10

Is there log files somewhere maybe? so i could send you the error?

**Comment by samlhuillier** [comment]
Working on this right now and it will be ready tomorrow morning. 
If you wanted to check the logs right now though you could just clone the repo and run ```npm run dev```. The error will appear in the console logs.

**Comment by samlhuillier** [comment]
I have released a version which'll show a high level error message [here](https://github.com/reorproject/reor/releases/download/v0.1.32/Reor_0.1.32.exe). 
Something else I thought of is that this issue may just be that it is taking a while to load the model into memory...Maybe you could also try a small model like [tinyllama](https://huggingface.co/TheBloke/TinyLlama-1.1B-Chat-v0.3-GGUF) to see if the issue is in fact related to loading speeds.

**Comment by BenutzerEinsZweiDrei** [comment]
Thanks i will try with tinyllama
