### ISSUE TITLE
Linux AppImage is nearly exactly 500.00MB big

### ISSUE THREAD

**Issue by sebastian-philipp** [reorproject/reor#236]
```
➜  bin ll Reor_0.2.7.AppImage 
-rwxr-xr-x. 1 sebastian sebastian 500M  5. Mai 12:33 Reor_0.2.7.AppImage
➜  bin ls -l Reor_0.2.7.AppImage
-rwxr-xr-x. 1 sebastian sebastian 524241405  5. Mai 12:33 Reor_0.2.7.AppImage
```

while the windows binary is about half the size. Is this correct?

**Comment by ossafe** [comment]
Appimage for linux is often bloaty by a few hundred MB as it bundles libraries and a runtime so that - like flatpacks - it "just works" on Linux, no matter what distro. 

The bloat is mentioned a lot in packages that use it. Windows and Mac don't have the distro issue, so they can use the system's native libraries, rather then putting them in the appimage blob.
