### ISSUE TITLE
Spell Checking

### ISSUE THREAD

**Issue by Lamer217** [reorproject/reor#258]
I've noticed that the Reor app currently does not have any spell-checking functionality. I'm wondering if this is a feature that has not yet been implemented, or if it is an intentional design choice?

Rationale:
As the app is focused on taking notes, I believe that having spell-checking would be a valuable feature. Ensuring correct spelling is important for note-taking, as it enhances the readability and professionalism of the notes.

Proposal:
I propose adding spell-checking functionality to the Reor app. This could be implemented as an optional feature that users can enable or disable based on their preference.

Thank you for considering this feature request.

**Comment by samlhuillier** [comment]
Thank you for mentioning this!

Yes this is something that we definitely can add. It was removed a couple of weeks back so that the welcome message (in English) would not just show a bunch of spelling errors to users with non-English machines.

It'll need to be added in settings as a toggle which saves the spellcheck preference in settings. Would you be interested in contributing to this feature? I'd love to see a contribution from you and I can help out where needed :)

**Comment by sebastian-philipp** [comment]
Maybe relates to https://github.com/reorproject/reor/issues/237 ?

**Comment by weilirs** [comment]
I'll see if I can help with this, would love to contribute!

**Comment by samlhuillier** [comment]
Just a little pointer @weilirs you'll see spellcheck was disabled in use-file-by-filepath.ts:
```
spellcheck: "false"
```

**Comment by weilirs** [comment]
For this feature, is it better to have a "General" page in the settings to manage preferences like this? I don't know if it is crucial enough to have a page itself like "Chunk Size". 

Also, this preference needs to be added to electron store?

**Comment by samlhuillier** [comment]
Yes I completely agree with you although I'd suggest a different categorisation: chunk size should really be part of RAG settings and spellcheck could be under either "Editor Settings" or "General" - your call
