### ISSUE TITLE
Windows11-Index error: TypeError: fetch failed

### ISSUE THREAD

**Issue by GuoJiaxing1997** [reorproject/reor#66]
The first time when i want to start the app
![image](https://github.com/reorproject/reor/assets/88412036/cbb466cd-4dd2-4867-be65-9486ceb7f8e4)

**Comment by samlhuillier** [comment]
Looking into it. Are you behind some kind of proxy or vpn?

**Comment by samlhuillier** [comment]
Ok. Are you aware of any strategies for dealing with this for in app downloads? Reor attempts to download the embedding model from huggingface and it seems to fail due to proxies like this. 

(I am working on allowing for manual downloads right now but would want to make automatic downloads work well too)

**Comment by GuoJiaxing1997** [comment]
Actually, I personally downloaded the LLM from Huggingface and added it to the "local LLM." However, when it comes to the embedding model, I didn't do anything; I just kept it as the default. Could it be that it's unable to download the embedding model properly?
![Snipaste_2024-02-22_07-57-21](https://github.com/reorproject/reor/assets/88412036/7b192b2d-601e-46e6-ae9b-e1ee2d651229)
![Snipaste_2024-02-22_08-01-40](https://github.com/reorproject/reor/assets/88412036/c0f7c4f5-559a-4c92-8e99-7befc162059c)

**Comment by samlhuillier** [comment]
Yes it is that. I am adding the feature to allow manual embedding model downloads too to deal with this

**Comment by samlhuillier** [comment]
I have just released a [new version](https://github.com/reorproject/reor/releases/tag/v0.1.49) that allows you to download an embedding model from huggingface and attach it yourself to get around this error which is caused by not using the system proxy when download the embedding model from hugging face. 

And a guide to doing this is [here](https://www.reorproject.org/docs/documentation/embedding).

I am also working on a fix to get around the proxy issues as we speak :)

**Comment by GuoJiaxing1997** [comment]
Thanks, I will try

**Comment by samlhuillier** [comment]
@GuoJiaxing1997 Now pushed out a fix for the proxy issues which should fix this error message entirely, download the model automatically and get rid of this error: https://github.com/reorproject/reor/releases/tag/v0.1.50

**Comment by GuoJiaxing1997** [comment]
It works, thanks!
